version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.14-browsers

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: yarn install
        

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: 
        command: docker run -v `pwd`:/testcafe-ci-demo -it testcafe/testcafe chromium /testcafe-ci-demo/tests/test.js

      - store_test_results:
          path: /tmp/test-results